### ISSUE TITLE
Překlad fungují jen v development módu

### ISSUE THREAD

**Issue by soundake** [positivezero/gettext-translator#1]
Ahoj, zkouším toto rozšíření, ale překlady mi fungují pouze v development módu a přestanou fungovat v módu jiném. Resp. přestanou fungovat po zakomentování $configurator->setDebugMode(...).

Netušíš čím by to mohlo být?

**Comment by soundake** [comment]
Tak to bylo zřejmě keší.

**Comment by positivezero** [comment]
Doporucuji stavajici verzi gettexttranslatoru nepouzivat s cache. Nas fork puvodniho schmutzka/gettexttranslator momentalne neobsahuje zadnou zaplatu, ktera se cache tyka.  
Stava se nam zcela nepredvidatelne, ze si gettext chybne interpretuje nacteni zdrojovych jazykovych souboru a po te zobrazuje web bez prekladu.

**Comment by soundake** [comment]
Chystáte nějakou opravu?

**Comment by positivezero** [comment]
Časem určitě, ale máme teď na programu bohužel jiné věci. Můžes poslat pull request...
